name: CompulsorySummons
version: 1.2
main: net.kunmc.lab.compulsorysummons.CompulsorySummonsPlugin
api-version: 1.16
author: stcYps
website: https://github.com/TeamKun/CompulsorySummons
commands:
  compulsorysummons:
    description: CompulsorySummonsPlugin Main Command
    usage: /compulsorysummons <引数>
    permission: op